spring:
  datasource:
    type:  com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;DatabaseName=George
    username: sa
    password: f10011116

  devtools:
    restart:
      enabled: true  
