spring:
  datasource:
    type:  com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://10.164.25.149:1433;DatabaseName=MetLifeEmail
    username: mlemail
    password: Admin1234

  devtools:
    restart:
      enabled: true  
